apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: 
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: 
  imagePullPolicy: Never
  mainApplicationFile: local:///app/
  sparkVersion: "3.3.1"
  arguments:
  - "{{ ts }}"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "2000m"
    memory: "2048m"
    labels:
      version: 3.3.1
    serviceAccount: spark
  executor:
    cores: 1
    memory: "16384m"
    instances: 1
    labels:
      version: 3.3.1
  dynamicAllocation:
    enabled: true
    initialExecutors: 2
    minExecutors: 2
    maxExecutors: 2
  deps:
    jars: